language: java

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - David.Dunphy@verint.com
    on_success: never
    on_failure: change

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

after_install:
    ./gradlew sonarqube \
       -Dsonar.host.url=https://sonarcloud.io \
       -Dsonar.organization=rddunphy-github \
       -Dsonar.login=dde7ec0ce44964335d19eb4cbb66ae49e112bf45