language: java
jdk:
- oraclejdk8
sudo: false
install: true
notifications:
  email:
    recipients:
    - David.Dunphy@verint.com
    on_success: never
    on_failure: change
branches:
  only:
  - master
before_install:
- chmod +x gradlew
script:
- "./gradlew sonarqube"
addons:
  sonarqube:
    organization: rddunphy-github
    token:
      secure: sfw8NTLngeggRLGK/NR0wuTB+DwEgGdO7WVYpypr2M3tyQ6aC/6RMGOY6pcHEy2C0dJYevY1jRFlGmbXtqpY2NB5Lp/9RXV2IDfa/20PVywPJZu0YKXyHF52rFk09NvVJI1Fhtjp1aMn+Tkag8kYp4O3r1MOqHsvtiGJ16Pds1WeAFv1maYtWO5jKd1MLScS5aFj87cnDtL2utgT33/3VM4goXQF3msaXMrNb3KUrFRBuKq0OFvkYtrAuyir0cyuDv2+r3JDV8VDa40BI3ZYDLzXcrPb39HbXuiNpFMMifUpAkMyRUf9A3rMRbxUDvIzmL3GoEsdFvsmg4L9tgcVhdLxBi/cwae89mr/oUFTcRK8Kf3YieRTzgeqAdKf97E4YSuIpE9gjN0Ph4jPkPUCNxcA5Ty28FxO72t+lfMHq7qYmJ71TXgOCIZvj/zp3+vZwrnoT9H/G28WBSO7GU3y3qglEPU8kvalHj9UF1gcb3a/33XKmmIKLa2TTYLYiBAu4oAiewDhmmENWqoY7haw0F83hcyFSuAjsygNJQ7pE4ZUAeoHnoKyS4kGcjLu9ZFhxJJgzgOX061utuh58ClNHg/oW9vTyBREdeH8Hr/4OD6Mhb6TEvT8QNIvjvi1R4ugLvlAMAyUbh4t81fMWg8jsBIR66XXhth1tDH7+H6MMeU=

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
  