language: java

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - David.Dunphy@verint.com
    on_success: never
    on_failure: change

branches:
  only:
    - master

before_install:
  - chmod +x gradlew